### ISSUE TITLE
Updating docs in github:lfortran doesn't trigger build in this repository

### ISSUE THREAD

**Issue by tapaswenipathak** [lfortran/docs.lfortran.org#1]
Example: https://github.com/lfortran/lfortran/pull/7.

<img width="1255" alt="Screenshot 2022-07-20 at 12 44 44 PM" src="https://user-images.githubusercontent.com/4143778/179920166-7a158e48-e6c3-417a-ab67-62ba6de764a9.png">

still has GitLab URL. 
<img width="1082" alt="Screenshot 2022-07-20 at 12 45 21 PM" src="https://user-images.githubusercontent.com/4143778/179920291-c1de8234-7495-47e8-9f86-0266cfda917a.png">

cc @certik.

**Comment by certik** [comment]
Yes, we are working on this. It has to be implemented in the CI.
